### ISSUE TITLE
Google Colab Issue

### ISSUE THREAD

**Issue by hexaaagon** [menukaonline/goindex-extended#80]
![image](https://user-images.githubusercontent.com/128217934/230038927-def705ac-3e84-46ad-bf12-48438e689bc3.png)

i got a error in the Google Colab GoIndex Extended Code generation.

i got the token in [this](https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?client_id=202264815644.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A1%2F&response_type=code&access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&approval_prompt=auto&service=lso&o2v=1&flowName=GeneralOAuthFlow) oauth2 web, i dunno is the token is broke or the code.

**Comment by hexaaagon** [comment]
uh, human error lmfao

**Comment by menukaonline** [comment]
I think this is because Google recently deprecated the authentication method used in this Colab notebook. Until I fix this, you can use the manual method. This may take a little time because I'm currently working on the documentation. After the documentation is completed, I will fix this.

**Comment by hexaaagon** [comment]
> 

Thank you for your reply, but i still confused cause how to get the encryption code.

**Comment by menukaonline** [comment]
Basically, `crypt_secret` is used as the secret key for the symmetric encryption implemented in this script. Hope you will understand what it is by having a look at the following uses.

---

`crypt_secret` was initially introduced to encrypt file ids (https://github.com/menukaonline/goindex-extended/issues/24#issuecomment-938866533).

---

Later, the search functionality for `folder root type` was added (which is not yet available in the Google Drive API). To make this operation possible, this function uses the file tree of the root folder generated from this Colab notebook: [Folder_Id_List_Generator.ipynb](https://colab.research.google.com/github/cheems/goindex-extended/blob/master/generators/Folder_Id_List_Generator.ipynb). (due to the deprecated authentication method, I think this doesn't work at the moment)

If you have a huge file tree containing many directory levels and thousands of files under the root folder that you added to the goindex-extended script, the generated file tree could be very long. Because of this, it is [instructed](https://github.com/menukaonline/goindex-extended#-configure-search-functionality-for-folders) to host the file tree somewhere and add its URL to the goindex-extended script.

Since the file tree needs to be hosted publicly, the above Colab notebook encrypts the file tree using your `crypt_secret` before displaying the file tree to you for copying.

---

So this script can access the file tree by decrypting the ciphertext you hosted whenever the end users perform a search.

This is the 2nd use of `crypt_secret`.

---

In the upcoming updates(not in the next update but later ones), crypt_secret will be used to save cookies (encrypted strings) in users' browsers, so this script will be able to load files more quickly and reduce loading errors.

---

For better encryption, it needs a strong secret key. Therefore, several requirements were listed to make `crypt_secret` stronger and more complex.

In order to make `crypt_secret` stronger, it must
 - be 32 characters in length
 - consist of
   - letters (in both lower and uppercase)
   - numbers
   - symbols (Excluded symbols: `\` `/` `"` `'`)

_**Note:** Avoid using excluded symbols `\` `/` `"` `'` as they may conflict with the code._

The concept is the same as creating a password. Here are some examples:
 - `1234567890123456abcdefghIJKLMN!*`
 - `0259P!f1d%Q@KbB#^z@oY5xm5tm4hhiL`
 - `AJoZ&2jQU6AMR9x@C5PXJ$ayV&WQVGi*`

You can also use your favourite password generator to create a strong `crypt_secret`.
<details>
<summary>A screenshot of password generator in Bitwarden</summary>

![image](https://user-images.githubusercontent.com/28010975/230144650-b1d064cf-d1e3-49e4-a28d-abc0a7d8f9d7.png)

</details>

**Comment by hexaaagon** [comment]
Okay, thank you for your help, i understand now. Thanks again for your support!
